name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.PTEST }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths