name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.PTEST }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths


# jobs:
#   build-and-deploy:
#     name: Build and deploy Gatsby site
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2.3.1
      
#       - name: Install Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '13.x'
      
#       - name: Install Project Dependencies
#         run: npm ci
      
#       - name: Install Gatsby CLI
#         run: npm install -g gatsby-cli
      
#       - name: Build
#         run: gatsby build
      
#       - name: Verify build
#         run: ls -la public